FilmNet/MovieApp.Web/Models/HomePageViewModel.cs
using MovieApp.Web.Entitiy;
using System.Collections.Generic;

namespace MovieApp.Web.Models
{
    public class HomePageViewModel
    {
        public List<Movie> PopularMovies { get; set; }
    }
}

FilmNet/MovieApp.Web/Models/MoviesViewModel.cs
using MovieApp.Web.Entitiy;
using System.Collections.Generic;

namespace MovieApp.Web.Models
{
    public class MoviesViewModel
    {
        public List<Movie> Movies { get; set; }       
    }
}

FilmNet/MovieApp.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MovieApp.Web.Data;
using MovieApp.Web.Models;
using System.Collections.Generic;
using System.Linq;

namespace MovieApp.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly MovieContext _context;

        public HomeController(MovieContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var model = new HomePageViewModel
            {
                PopularMovies = _context.Movies.ToList()
            };

            return View(model);
        }

        public IActionResult About()
        {
            
            return View();
        }
    }
}

FilmNet/MovieApp.Web/Controllers/MoviesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MovieApp.Web.Data;
using MovieApp.Web.Entitiy;
using MovieApp.Web.Models;
using System.Collections.Generic;
using System.Linq;

namespace MovieApp.Web.Controllers
{
    public class MoviesController : Controller
    {
        private readonly MovieContext _context;

        public MoviesController(MovieContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult List(int? id,string q)
        {

            //var controller = RouteData.Values["controller"];
            //var action = RouteData.Values["action"];
            //var genreid = RouteData.Values["id"];
            //var kelime = HttpContext.Request.Query["q"].ToString();

            //var movies = MovieRepository.Movies;
            var movies = _context.Movies.AsQueryable();

            if (id != null)
            {
                movies = movies.Where(m=>m.GenreId == id);
            }

            if (!string.IsNullOrEmpty(q))
            {
                movies = movies.Where(i=>
                i.Title.ToLower().Contains(q.ToLower()) ||
                i.Description.ToLower().Contains(q.ToLower()));
            }

            var model = new MoviesViewModel()
            {
                Movies = movies.ToList()
            };

            return View("Movies",model);
        }
        public IActionResult Details(int id)
        {
            return View(_context.Movies.Find(id));
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Genres = new SelectList(_context.Genres.ToList(), "GenreId", "Name");
            return View();
        }
        [HttpPost]
        public IActionResult Create(Movie m)
        {
            if (ModelState.IsValid)
            {

                //MovieRepository.Add(m);
                _context.Movies.Add(m);
                _context.SaveChanges();
                TempData["Message"] = $"{m.Title} isimli film eklendi.";
                return RedirectToAction("List");
            }
            ViewBag.Genres = new SelectList(_context.Genres.ToList(), "GenreId", "Name");
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Genres = new SelectList(_context.Genres.ToList(), "GenreId", "Name");
            return View(_context.Movies.Find(id));
        }
        [HttpPost]
        public IActionResult Edit(Movie m)
        {
            if (ModelState.IsValid)
            {
                //MovieRepository.Add(m);
                _context.Movies.Update(m);
                _context.SaveChanges();
                return RedirectToAction("Details", "Movies", new { @id = m.MovieId });
            }
            ViewBag.Genres = new SelectList(_context.Genres.ToList(), "GenreId", "Name");
            return View(m);
            
        }

        [HttpPost]
        public IActionResult Delete(int MovieId,string Title)
        {
            //MovieRepository.Delete(MovieId);
            var entity = _context.Movies.Find(MovieId);
            _context.Movies.Remove(entity);
            _context.SaveChanges();
            TempData["Message"] = $"{Title} isimli film silindi.";
            return RedirectToAction("List");

        }
    }
}

FilmNet/MovieApp.Web/ViewComponents/GenresViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MovieApp.Web.Data;
using MovieApp.Web.Models;
using System.Collections.Generic;
using System.Linq;

namespace MovieApp.Web.ViewComponents
{
    public class GenresViewComponent: ViewComponent
    {
        private readonly MovieContext _context;

        public GenresViewComponent(MovieContext context)
        {
            _context = context;
        }
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedGenre = RouteData.Values["id"];
            return View(_context.Genres.ToList());
        }
    }
}

FilmNet/MovieApp.Web/Views/Home/About.cshtml
@model List<Genre>

<p>Home/About</p>    

@section menu
{
    @await Html.PartialAsync("_menu",Model)
    @* @await Component.InvokeAsync("Genres") *@
}

FilmNet/MovieApp.Web/Views/Home/Index.cshtml
@model HomePageViewModel

@section header
{
    @await Html.PartialAsync("_header")
}
@section scripts
{
    <script src="~/js/scripts.js"></script>
}
    <h1>Film Listesi</h1>
    <div id="filmler">
        @foreach (var movie in Model.PopularMovies)
    {
        @await Html.PartialAsync("_movie", movie)
    }
        

    </div>

FilmNet/MovieApp.Web/Views/Movies/Create.cshtml
@model Movie

<h1>Create Movie</h1>

<hr />

<form method="post" asp-controller="Movies" asp-action="Create">
    <div class="form-group">
        <label asp-for="Title"></label>
        <input asp-for="Title" class="form-control"/>
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <textarea asp-for="Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ImageUrl"></label>
        <input asp-for="ImageUrl" class="form-control" />
        <span asp-validation-for="ImageUrl" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="GenreId"></label>
        <select asp-for="GenreId" asp-items="@ViewBag.Genres" class="form-control">
            <option selected disable>Seçiniz</option>
        </select>
        <span asp-validation-for="GenreId" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

FilmNet/MovieApp.Web/Views/Movies/Details.cshtml
@model Movie

<div class="card">
    <div class="row">
        <div class="col-md-3">
            <img src="/img/@Model.ImageUrl" class="card-img"/>
        </div>
        <div class="col-md-9">
            <div class="card-body">
                <h5 class="card-title">@Model.Title</h5>
                <p class="card-text">@Model.Description</p>
                @* @if (Model.Players != null)
                {                                    
                    <p>
                        <ul>
                            @foreach (var item in Model.Players)
                            {
                                <li>@item</li>
                            }
                        </ul>
                    </p>
                } *@
            </div>
        </div>
    </div>
</div>

FilmNet/MovieApp.Web/Views/Movies/Edit.cshtml
@model Movie

<h1>Edit Movie</h1>

<hr />

<form method="post" asp-controller="Movies" asp-action="Edit">
    <input type="hidden" name="MovieId" value="@Model.MovieId" />
    <div class="form-group">
        <label asp-for="Title"></label>
        <input asp-for="Title" class="form-control" value="@Model.Title"/>
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <textarea asp-for="Description" class="form-control">@Model.Description</textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ImageUrl"></label>
        <input asp-for="ImageUrl" class="form-control" value="@Model.ImageUrl" />
        <span asp-validation-for="ImageUrl" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="GenreId"></label>
        <select asp-for="GenreId" asp-items="@ViewBag.Genres" class="form-control">
            <option selected disable>Seçiniz</option>           
        </select>
        <span asp-validation-for="GenreId" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

FilmNet/MovieApp.Web/Views/Movies/Index.cshtml
<p>
    movies/index
</p>

FilmNet/MovieApp.Web/Views/Movies/Movies.cshtml
    @model MoviesViewModel

    <h1>Film Listesi</h1>


    <div id="filmler">
    @if (Model.Movies.Count() > 0)
    {
        @foreach (var movie in Model.Movies)
        {
            @await Html.PartialAsync("_movie", movie)
        }
    }
    else
    {
        <div class="alet alert-warning">
            Film bulunamadı.
        </div>
    }

    </div>
@if (TempData["Message"] != null)
{
    @section message
    {
    @await Html.PartialAsync("_message", (string)TempData["Message"])
    }
}

    
    @section menu 
    {
    @* @await Html.PartialAsync("_menu",Model.Genres) *@
    @await Component.InvokeAsync("Genres")
    }

FilmNet/MovieApp.Web/Views/Shared/Components/Genres/Default.cshtml
@model List<Genre>

<div class="list-group">
    <a href="/movies/list" class="list-group-item list-group-item-action 
    @(ViewBag.SelectedGenre==null ? "active" : "")">
        Tüm filmler</a>

    @foreach (var genre in Model)
    {
        <a href="/movies/list/@genre.GenreId" 
        class="list-group-item list-group-item-action 
        @(ViewBag.SelectedGenre == genre.GenreId.ToString()? "active" : "")">
        @genre.Name</a>
    }

</div>

FilmNet/MovieApp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="/css/style.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
</head>
<body>

    @RenderSection("message",false)
    @await Html.PartialAsync("_navbar")
    @RenderSection("header",false)

    
    <div class="container mt-3">

        @if (IsSectionDefined("menu"))
        {
            <div class="row">
                <div class="col-md-3">
                    @RenderSection("menu",false)
                </div>
                <div class="col-md-9">
                    @RenderBody()
                </div>
            </div>
        }
        else
        {
            <div class="row">
                <div class="col-md-12">
                    @RenderBody()
                </div>
            </div>
        }

       

        
        
    </div>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    @RenderSection("scripts",false)
</body>
</html>

FilmNet/MovieApp.Web/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="/css/style.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarToggler">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggler">
                <a href="#" class="navbar-brand">FilmNet</a>
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a href="/movieslist" class="nav-link">İçerik</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div>
        @RenderBody()
    </div>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

</body>
</html>

FilmNet/MovieApp.Web/Views/Shared/_header.cshtml
<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4">Size göre en özel filmler</h1>
        <p class="lead">Onlarca film arasından seçim yapmanızı, kendi listelerinizi oluşturmanızı ve arkadaşlarınızla paylaşmanızı sağlayan bir platformdur. Hemen keşfetmeye başlayın!</p>
    </div>
</div>

FilmNet/MovieApp.Web/Views/Shared/_menu.cshtml
@model List<Genre>


<div class="list-group">
    @foreach (var genre in Model)
    {
        <a href="#" class="list-group-item list-group-item-action">@genre.Name</a>
    }
    
</div>

FilmNet/MovieApp.Web/Views/Shared/_message.cshtml
@model String

<div class="alet alert-success mb-0 text-center">
    @Model 
</div>

FilmNet/MovieApp.Web/Views/Shared/_movie.cshtml
@model Movie

<div class="card mb-3 ">
    <div class="row">
        <div class="col-md-4">
            <img id="resim" src="/img/@Model.ImageUrl" alt="@Model.Title" />
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">@Model.Title</h5>
                <div>
                    <a class="btn btn-primary" asp-controller="Movies" asp-action="Details"
                       asp-route-id="@Model.MovieId">İncele</a>
                    <a class="btn btn-warning" asp-controller="Movies" asp-action="Edit"
                       asp-route-id="@Model.MovieId">Düzenle</a>
                    
                    <form asp-controller="Movies" asp-action="Delete" method="post" style="display:inline">
                        <input type="hidden" name="Title" value="@Model.Title" />
                        <input type="hidden" name="MovieId" value="@Model.MovieId" />
                        <button type="submit" class="btn btn-danger">Sil</button>
                    </form>
                    
                   
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    #resim {
        width: 179px;
    }
</style>

FilmNet/MovieApp.Web/Views/Shared/_navbar.cshtml
<nav class="navbar navbar-expand-lg navbar-dark bg-danger">
    <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarToggler">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggler">
            <a href="/" class="navbar-brand">FilmNet</a>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a href="/movies/list" class="nav-link">Filmler</a>
                </li>
                <li class="nav-item">
                    <a href="/movies/create" class="nav-link">Film kaydet</a>
                </li>
            </ul>

            <form action="/movies/list" method="get" class="form-inline">
                <input type="text" name="q" placeholder="Film ara" class="form-control mr-2"/>
                <button type="submit" class="btn btn-outline-light mr-0">Bul</button>
            </form>

        </div>
    </div>
</nav>